# Generated by Django 2.0.6 on 2018-07-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0002_auto_20180629_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='heineken', max_length=1000)),
            ],
        ),
    ]
